// <auto-generated />
using System;
using CollaborativeLearningAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollaborativeLearningAPI.Migrations
{
    [DbContext(typeof(CollaborativeLearningDBContext))]
    [Migration("20250120183149_StudentFeedbackRelation")]
    partial class StudentFeedbackRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<double>("ECTS")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("StudentId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourceId"));

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResourceId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("CoordinatorId")
                        .HasColumnType("int");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Hall")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time");

                    b.HasKey("ScheduleId");

                    b.HasIndex("CoordinatorId")
                        .IsUnique();

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Staff", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.StudentCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCourse");
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Tasks", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int?>("AssistantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskId");

                    b.HasIndex("AssistantId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CoursesCourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentsStudentId")
                        .HasColumnType("int");

                    b.HasKey("CoursesCourseId", "StudentsStudentId");

                    b.HasIndex("StudentsStudentId");

                    b.ToTable("CourseStudent");
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Assistant", b =>
                {
                    b.HasBaseType("CollaborativeLearningAPI.Models.Staff");

                    b.Property<bool>("AssistsInGrading")
                        .HasColumnType("bit");

                    b.Property<bool>("HelpsWithProjects")
                        .HasColumnType("bit");

                    b.Property<string>("ResearchField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Assistant", (string)null);
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Coordinator", b =>
                {
                    b.HasBaseType("CollaborativeLearningAPI.Models.Staff");

                    b.Property<string>("CertificationLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldOfExpertise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.ToTable("Coordinator", (string)null);
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Professor", b =>
                {
                    b.HasBaseType("CollaborativeLearningAPI.Models.Staff");

                    b.Property<string>("SubjectArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Professor", (string)null);
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Feedback", b =>
                {
                    b.HasOne("CollaborativeLearningAPI.Models.Student", "Students")
                        .WithMany("Feedbacks")
                        .HasForeignKey("StudentId");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Resource", b =>
                {
                    b.HasOne("CollaborativeLearningAPI.Models.Professor", "Professors")
                        .WithMany("Resources")
                        .HasForeignKey("ProfessorId");

                    b.Navigation("Professors");
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Schedule", b =>
                {
                    b.HasOne("CollaborativeLearningAPI.Models.Coordinator", "Coordinator")
                        .WithOne("Schedule")
                        .HasForeignKey("CollaborativeLearningAPI.Models.Schedule", "CoordinatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollaborativeLearningAPI.Models.Group", "Group")
                        .WithOne("Schedule")
                        .HasForeignKey("CollaborativeLearningAPI.Models.Schedule", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coordinator");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Student", b =>
                {
                    b.HasOne("CollaborativeLearningAPI.Models.Group", "Groups")
                        .WithMany("Students")
                        .HasForeignKey("GroupId");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.StudentCourse", b =>
                {
                    b.HasOne("CollaborativeLearningAPI.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.HasOne("CollaborativeLearningAPI.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Tasks", b =>
                {
                    b.HasOne("CollaborativeLearningAPI.Models.Assistant", "Assistant")
                        .WithMany("Tasks")
                        .HasForeignKey("AssistantId");

                    b.Navigation("Assistant");
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("CollaborativeLearningAPI.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollaborativeLearningAPI.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Assistant", b =>
                {
                    b.HasOne("CollaborativeLearningAPI.Models.Staff", null)
                        .WithOne()
                        .HasForeignKey("CollaborativeLearningAPI.Models.Assistant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Coordinator", b =>
                {
                    b.HasOne("CollaborativeLearningAPI.Models.Staff", null)
                        .WithOne()
                        .HasForeignKey("CollaborativeLearningAPI.Models.Coordinator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Professor", b =>
                {
                    b.HasOne("CollaborativeLearningAPI.Models.Staff", null)
                        .WithOne()
                        .HasForeignKey("CollaborativeLearningAPI.Models.Professor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Group", b =>
                {
                    b.Navigation("Schedule")
                        .IsRequired();

                    b.Navigation("Students");
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Student", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Assistant", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Coordinator", b =>
                {
                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("CollaborativeLearningAPI.Models.Professor", b =>
                {
                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
